### ISSUE TITLE
SoupX / Cite-seq?

### ISSUE THREAD

**Issue by bbimber** [constantAmateur/SoupX#101]
Hello - have you used SoupX on CITE-seq data? Similar tools, like cellbender, report that they can be used to remove background noise for ADTs.

**Comment by constantAmateur** [comment]
I haven't looked into how ADTs behave and if they need to be treated differently from mRNAs.  There is nothing stopping you running cite-seq data and treating ADTs as if they were just another mRNA, but I really don't know how well this will work and so I can't recommend it at the moment.  I'd suggest removing the ADTs from your matrix and processing the data as if it were just scRNA data.

**Comment by jamesdahlvang** [comment]
FYI--John Tsang's lab developed a tool called DSB that works by measuring the amount of ambient ADT in soup and using that as the benchmark for protein expression data. I have found it works quite well.
