### ISSUE TITLE
SoupX and normalization in Seurat

### ISSUE THREAD

**Issue by tkapello** [constantAmateur/SoupX#104]
I was wondering how a SoupX'ed count matrix should be treated for downstream analysis with the Seurat pipeline. Seurat uses raw integers for normalization, would it be alright to use the corrected counts from SoupX as the input for normalization?

**Comment by constantAmateur** [comment]
The Seurat normalisation is conceptually similar to generating TPMs and so will work fine with a SoupX corrected count matrix.
