### ISSUE TITLE
pointSize in plotChangeMap is fixed to 0.5 when dataType == "soupFrac"

### ISSUE THREAD

**Issue by Close-your-eyes** [constantAmateur/SoupX#105]
The title says it,

SoupX::plotChangeMap(sc, out, geneSet = "GNLY", pointSize = 10, dataType = "counts") # does work (large points)
SoupX::plotChangeMap(sc, out, geneSet = "GNLY", pointSize = 10, dataType = "soupFrac") # does not work (point size unaffected)

In the code one can see that 0.5 is hard-coded in the soupFrac-part of the function.

I think this is unintended.

I use the CRAN version.

**Comment by constantAmateur** [comment]
Thanks.  This will be fixed.
