### ISSUE TITLE
Isssue of 'toc' and tod"

### ISSUE THREAD

**Issue by kathywawa** [constantAmateur/SoupX#106]
Hi, Professors,
I have some questions to ask you.
First, what files do I need to prepare for analyzing SoupX.
Next, how can I set up toc and tod when I analyze my own single-cell sequencing data.
Thanks.
kathy

**Comment by constantAmateur** [comment]
toc is short for table of cells and should include only those barcodes that contain cells (e.g. the filtered counts folder in the cellranger output).
tod is short for table of droplets and should include all barcodes (e.g. the raw counts folder in the cellranger output).
