### ISSUE TITLE
quickMarkers specify clusters to compare

### ISSUE THREAD

**Issue by parkjooyoung99** [constantAmateur/SoupX#109]
Hello, 
I am currently using quickMarkers() for cluster annotation. 
Though sometimes I need to compare part of the clusters to find the difference between similar cell types.
Is there any way to do the same thing with 'FindMarkers(ident.1=3, ident.2=c(6,7,8))' in seurat, except for data subset? 

Thank you!

**Comment by constantAmateur** [comment]
Yes there is, although it's a bit more fiddly.  Supposing you would run this to find markers between all cell types:
```
mrks = quickMarkers(toc,clusters)
```
then to compare just clusters 6,7, and 8, you would do
```
w = which(clusters %in% c(6,7,8))
mrks = quickMarkers(toc[,w,drop=FALSE],clusters[w])
```
