### ISSUE TITLE
Using SoupX for dropseq data

### ISSUE THREAD

**Issue by yolsan** [constantAmateur/SoupX#11]
Hi,
I would like to use SoupX for my dropseq data. Is it possible to just plug the dgTMatrix to estimate Soup?

Best,
Yolanda

**Comment by constantAmateur** [comment]
Hi Yolanda,

All that SoupX needs to work is a sparse matrix containing counts for each gene from all droplets generated in the experiment (including empty ones) and a vector indicating which of these droplets contain cells.  If the dgTMatrix you provide meets these criteria there is no reason it shouldn't work.  Have a look at the help for `SoupChannel` for details of how to load the data.
