### ISSUE TITLE
Working with inaccurate cell calling data

### ISSUE THREAD

**Issue by RuiyuRayWang** [constantAmateur/SoupX#115]
Due to the nature of my bio sample, CellRanger's cell calling is inaccurate and my filtered_feature_bc_matrix contains many empty droplets.

I was able to confirm this because in my umap there is a cluster showing very low number of gene numbers and very high level of mitochondrial transcripts.
<img width="862" alt="Screen Shot 2022-06-22 at 13 12 33" src="https://user-images.githubusercontent.com/12589928/174948718-3403a57d-b87a-42dc-ae38-094fb0215d45.png">

Tuning the `--force-cells` parameter in cellranger is difficult because it's hard to find the exact threshold for calling a cell a cell. See my barcode rank plot below:
![newplot2](https://user-images.githubusercontent.com/12589928/174706012-f2b37908-8463-4116-955c-e20f7a535b17.png)

My question is, can SoupX work with data like this?
Should I manually remove the empty droplet population before or after SoupX?

Thanks!
Ray

**Comment by constantAmateur** [comment]
Broadly speaking it shouldn't matter much, as long as there are more real cells than miscalled empty cells.  Optimally you'd probably want to remove them before SoupX, but it really shouldn't make much difference.

If you'd like to check, try running SoupX twice with and without these cells and verify that the estimated contamination fraction is similar.
