### ISSUE TITLE
autoEstCont() error

### ISSUE THREAD

**Issue by joyduck** [constantAmateur/SoupX#118]
hi there,
 I tried to use SoupX manually by first reading in the raw and filtered count matrixes, to create a soup channel, then get the cluster info from Seurat, basically what is described here:
https://cellgeni.github.io/notebooks/html/new-10kPBMC-SoupX.html

an error occurred when executing the command:   soup.channel <- autoEstCont(soup.channel)

"Error in quantile.default(soupProf$est, soupQuantile) :  missing values and NaN's not allowed if 'na.rm' is FALSE"

 I could not figure out why the est were all calculated as Nans, please help
count matrix was generated from cellranger 6.1.3, not sure if the version matters.

Thanks

**Comment by xzhouaw** [comment]
I am facing the same problem with manually loaded matrix. Could I know how you solved it?

**Comment by JS0715** [comment]
Getting the same error. How did you fix this?
