### ISSUE TITLE
Should I run this before or after imputation?

### ISSUE THREAD

**Issue by ayeTown** [constantAmateur/SoupX#119]
Hi there,
Should SoupX be run before or after imputation? I am using the ALRA methodology for imputation: https://github.com/KlugerLab/ALRA 
Thanks for your input.
AT

**Comment by constantAmateur** [comment]
Run SoupX first, unless you have some particular reason to want to impute on contaminated data.  If ALRA requires counts as inputs make sure to set `roundToInt=TRUE` when running `adjustCounts`
