### ISSUE TITLE
Deprecated method from package "Matrix"

### ISSUE THREAD

**Issue by mvfki** [constantAmateur/SoupX#120]
Hi,

I have written a wrapper function to run SoupX on SCE objects. Recently it is failing on `quickMarkers()` step. Basically the traceback message looks like this:

```
Error: as(<dgCMatrix>, "dgTMatrix") is deprecated since Matrix 1.5-0; do as(., "TsparseMatrix") instead
8.
warning.(gettextf("as(<%s>, \"%s\") is deprecated since Matrix 1.5-0; do %s instead", 
cln1, cln2, deparse1(.as.via.virtual(Class1, Class2, quote(.)))), 
call. = FALSE, domain = NA)
7.
Matrix.DeprecatedCoerce(cd1, cd2)
6.
asMethod(object)
5.
as(toc, "dgTMatrix")
4.
quickMarkers(sc$toc, sc$metaData$clusters, N = Inf)
3.
SoupX::autoEstCont(sc, doPlot = FALSE, tfidfMin = tfidfMin, soupQuantile = soupQuantile, 
maxMarkers = maxMarkers, contaminationRange = contaminationRange, 
rhoMaxFDR = rhoMaxFDR, priorRho = priorRho, priorRhoStdDev = priorRhoStdDev, 
forceAccept = forceAccept)
```

My Rd example has this step in a "dontrun" section so the R CHECKs look OK for now, but in real use cases, I cannot use it anymore. 

Not only my own wrapper function, but the example code in your vignette also fails in the same place. Would you please kindly be able to look at this issue?

Best

**Comment by mvfki** [comment]
P.S.

```
> packageVersion("SoupX")
[1] '1.6.1'
> packageVersion("Matrix")
[1] '1.5.1'
```

**Comment by constantAmateur** [comment]
This is an issue created by an update in the Matrix package.  I will fix this soon, but in the meantime the workaround is to downgrade you Matrix package.

**Comment by constantAmateur** [comment]
This should now be fixed in 1.6.2 onwards.  Please reopen if you continue to get this warning.

**Comment by qianXX** [comment]
met same error with SoupX in 1.6.2 and Matrix in 1.5-3

**Comment by jvelghe** [comment]
Hi, I also met the same issue in SoupX 1.6.1, 1.6.2, and Matrix in 1.5.1, 1.5.4. It would be ideal to have this resolved. Thank you!
