### ISSUE TITLE
Question about rho_c

### ISSUE THREAD

**Issue by Hanxi-002** [constantAmateur/SoupX#121]
Hi there.

This isn't a question about running the package but about understanding the method. I wasn't sure where is more appropriate to ask. So thanks and apology in advance if this is the wrong forum for this. 

I'm trying to understand the method a bit more and is having trouble understanding rho_c. 
In the paper, rho_c is given as a fraction of 
**(\sum_g n_{g, c}) / (N_c * \sum_g b_g)**. 
In the previous section, the authors stated that 
**\sum_g n_{g, c} = N_c** .
So re-write rho_c to the following:
**(N_c) / (N_c * \sum_g b_g)**. 
Since b_g is the fraction of gene g in all empty droplets. Then sum over all genes will lead to \sum_g b_g to 1. 

Then rho_c would just always equal to 1. 

I know I'm missing something here but I can't figure out what it is. Any help is appreciated. Thank you!!

**Comment by constantAmateur** [comment]
The key here is the next sentence after the equations, "where the sum is taken across all genes in cell c for which it is assumed mg, c = 0".  So the sum in the equation for rho_c is not over all genes, but only those for which we assume m_g,c=0.
