### ISSUE TITLE
Using SoupX for indrops data (non 10x genomics output)

### ISSUE THREAD

**Issue by JoyOtten** [constantAmateur/SoupX#127]
Dear all,

I wanted to ask if we could use SoupX on data that is not delivered or run by 10x genomics. The problem that I have so far is that I don't have the filtered gene matrix, but I do have the raw gene matrix. I'm wondering if it's possible to create the filtered gene matrix yourself or run apart from the cellranger pipeline.

Thank you,
Joy

**Comment by nouhaylaeraysy** [comment]
Hello,
I started with SoupX me too i have the same problem did you manage to solve it?
please if you have an idea response me.
Thank you in advance.

**Comment by JoyOtten** [comment]
Hi,
I was able to construct a Seurat Object with the following lines of code if you're using R:

seurat <- CreateSeuratObject(counts, project = "name1", assay = "RNA",
                   min.cells = 0, min.features = 0, names.field = 1,
                   names.delim = "_", meta.data = metadata)

Basically I filtered the counts beforehand and then made a seurat object and put it into SoupX

**Comment by nouhaylaeraysy** [comment]
Hello, 
thank you for your response , actually I'm working with 3 libraries i want to apply soupx then integrate them , this is my code : 
ib1 <- readRDS("lib1_NoDoublet.rds")
lib2 <- readRDS("lib2_NoDoublet.rds")
lib3 <- readRDS("lib3_NoDoublet.rds")
reference_list <- c(lib1,lib2, lib3)
reference_list

lib1@meta.data


this is what i have in metadata of lib1 : 
 orig.ident nCount_RNA nFeature_RNA RNA_snn_res.0.8 seurat_clusters
AAACCCAAGACAGTCG-1       Lib1       1657          738               2               2
AAACCCAAGGTTCACT-1       Lib1       6227         2015               7               7
AAACCCACAACCAGAG-1       Lib1        844          463     
          0               0

pANN_0.25_0.3_951 DF.classifications_0.25_0.3_951
AAACCCAAGACAGTCG-1        0.08571429                         Singlet
AAACCCAAGGTTCACT-1        0.35801394                         Singlet



can you tell me how i can apply soupx for the 3 libraries? 
Thank you again.
Best

**Comment by JoyOtten** [comment]
Hi you need to apply SoupX separately for each library. Please read the paper accordingly and this might help you along. https://rawcdn.githack.com/constantAmateur/SoupX/204b602418df12e9fdb4b68775a8b486c6504fe4/inst/doc/pbmcTutorial.html

**Comment by nouhaylaeraysy** [comment]
Hi Thank you , 
i have just a filtred_features_bc_matrix i don't have a raw_feature_bc_matrix , so how i can find **tod** ?because in this paper they have 2 data : 
toc = Seurat::Read10X(file.path(tmpDir, "filtered_gene_bc_matrices", "GRCh38"))
tod = Seurat::Read10X(file.path(tmpDir, "raw_gene_bc_matrices", "GRCh38"))
