### ISSUE TITLE
Error while running strainCells

### ISSUE THREAD

**Issue by shr9st9** [constantAmateur/SoupX#16]
Hi, 

I run into following error while running strainCells. 

`Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In int2i(as.integer(i), n) : NAs introduced by coercion to integer range`

I don't see any NAs introduced in the dataset and it runs fine with smaller datasets.

Can you help in troubleshooting this?

Thanks
shristi

**Comment by constantAmateur** [comment]
Typically errors with NAs indicate an annotation error of some sort, but it is hard to tell without seeing the data.  Can you try on the updated version and re-open this ticket if you still have issues?
