### ISSUE TITLE
undesirable behavior reading in aggregated 10X data

### ISSUE THREAD

**Issue by ONeillMB1** [constantAmateur/SoupX#19]
Neat program you've developed here!

I would like to work form my downsampled data generated with cellranger aggr across several libraries. However, when I used the load10X() function everything is imported as one "Channel". The info is preserved in the barcode endings "-1"...."-10", but the cells are not being imported based on their respective channel/library.

**Comment by constantAmateur** [comment]
Loading aggregated information in this way is not supported by the `load10X` function.  You can manually construct the channels yourself using the SoupChannel function if you wish, or run SoupX on the un-aggregated data.
