### ISSUE TITLE
custom count matrixes

### ISSUE THREAD

**Issue by Eneritz** [constantAmateur/SoupX#2]
Hi Mathew,
I just starting using your method and I was wondering if it is possible to upload custom counts matrixes. I am using 10X samples but for some benchmarks instead of using cellranger output I have my own matrixes. Is it possible? Thanks.

Nice work

E

**Comment by constantAmateur** [comment]
Hi Eneritz,

Any count matrix should work, so long as it contains a column for each droplet.  The `load10X` function is really just a convenience, the key is running:

    channel1 = SoupChannel(tod1,toc1,channelName="NameOfChannel1")
    channel2 = SoupChannel(tod2,toc2,channelName="NameOfChannel2")
    scl = SoupChannelList(list(channel1,channel2))

where `tod` is the matrix with all droplets (including the empty ones) and `toc` is the sub-matrix that contains only the cell containing droplets.  This would be the `raw_gene_bc_matrices` and `filtered_gene_bc_matrices` respectively when using cellranger output.

`load10X` gets these for you from the cellranger output, if you're doing something else you'll have to construct them and input them manually as above.

**Comment by Eneritz** [comment]
Thanks Mathew!
