### ISSUE TITLE
multtest not available for R version 3.6.0

### ISSUE THREAD

**Issue by cswoboda** [constantAmateur/SoupX#21]
Hello, 

Just wanted to let you know that one of the dependencies of the updated package is outdated. I haven't tried running on an old form of R yet, but I'll let you know if it works. In case you see this before I do try and run this again, what version of R are you running for SoupX?

Thanks,

Casey

**Comment by maggietsui** [comment]
I ran into the same error but downloading multtest from bioconductor fixed it!

**Comment by constantAmateur** [comment]
This appears to be an issue with installing Seurat which can't be fixed from this end.  As suggested by @maggietsui the fix is to use bioconductor to install multtest.
