### ISSUE TITLE
[Question] Using soupX together with doublet detection tools

### ISSUE THREAD

**Issue by JonathanCruard** [constantAmateur/SoupX#24]
Hi, thanks for this great tool.

I'm testing various tools dedicated to scRNAseq data and I was wondering if you have any idea of the impact of soupX on the performance of doublet detection tools.

Thank you in advance.
JonathanCruard

**Comment by constantAmateur** [comment]
This is a good question that I haven't systematically investigated.  For now I'd recommend running your doublet detection first, getting a list of non-doubleted cells, then loading them using `SoupChannel` directly as per [this issue](https://github.com/constantAmateur/SoupX/issues/25#issuecomment-576190732).

**Comment by Xyanhong** [comment]
Interestingly, doublet detection methods like doublet finder requires an cleaned-up input for low-quaility data
