### ISSUE TITLE
plotMarkerDistribution(sc) error

### ISSUE THREAD

**Issue by chansigit** [constantAmateur/SoupX#26]
Can you please tell me what are the possible bugs with my code?

```
plotMarkerDistribution(sc)


Error in estimateNonExpressingCells(sc, as.list(gns), ...): Invalid cluster specification.  clusters must be a named vector with all column names in the table of counts appearing.
Traceback:

1. plotMarkerDistribution(sc)
2. inferNonExpressedGenes(sc, ...)
3. estimateNonExpressingCells(sc, as.list(gns), ...)
4. stop("Invalid cluster specification.  clusters must be a named vector with all column names in the table of counts appearing.")
```

**Comment by cswoboda** [comment]
Hey, 
Happy to help but will need session info and more details. It looks like an issue with the formatting of your Seurat_DR object. Could you show me the code for that object?
Casey

**Comment by chansigit** [comment]
I find the reason:
the cells supplied by seurat object is filtered when CreateSeuratObject
but SoupX read cells from cellranger filtered data.
their nRow conflict with each other.
