### ISSUE TITLE
\rho_c MLE deriviation

### ISSUE THREAD

**Issue by chansigit** [constantAmateur/SoupX#27]
Can you please tell me how shall I derive the MLE of \rho_c in 6.2.2 formula (5) of the manuscript?

Really appreciate for  your help.

**Comment by chansigit** [comment]
Especially, I am confused about "The maximum likelihood estimator (assuming a Poisson distribution) for \rho_c from a single cell is then just,". What does the Poisson distribution refers to?

**Comment by constantAmateur** [comment]
The manuscript will be updated shortly on biorxiv, which should make this clearer.  I'll close this for now.
