### ISSUE TITLE
why calling estimateSoup explicitly

### ISSUE THREAD

**Issue by chansigit** [constantAmateur/SoupX#28]
In the tutorial(https://cdn.rawgit.com/constantAmateur/SoupX/master/doc/pbmcTutorial.html), 
estimateSoup is called explicitly after constructing the SoupChannel.
```
sc = load10X(dataDirs, keepDroplets = TRUE)
sc = estimateSoup(sc)
```

but estimateSoup is actually called automatically in the following position
https://github.com/constantAmateur/SoupX/blob/d7c58f74324d3f83b13e3a4a3e73e6c4426307b2/R/classFunctions.R#L35

Why should we call it explicitly again?

**Comment by constantAmateur** [comment]
You should not.  This was included only to demonstrate what was being done automatically by the SoupChannel construction function.
