### ISSUE TITLE
load count matrix

### ISSUE THREAD

**Issue by icanwinwyz** [constantAmateur/SoupX#37]
Hi, 

Thanks for developing such a neat program. 
For the latest version, you removed the function "SoupChannelList", so how should I load the count expression matrix instead of 10X data from cellranger? Thanks.

**Comment by constantAmateur** [comment]
The function `SoupChannel` still exists and can be used to load any expression matrix.  SoupChannelList was intended for loading multiple channels simultaneously and has been removed to emphasise that channels should be processed one at a time.
