### ISSUE TITLE
Estimated global contamination fraction and cluster info

### ISSUE THREAD

**Issue by jmzvillarreal** [constantAmateur/SoupX#38]
Hi, 
I think I don't fully understand what Estimated global contamination fraction represents ¿the average conatmination fraction per droplet?
How would cluster information more accurately get rid of contamination ?
Thanks,
Jaime.

**Comment by constantAmateur** [comment]
Please refer to our manuscript that discusses the implementation in detail https://www.biorxiv.org/content/10.1101/303727v2

The global contamination fraction is the average fraction of molecules expected to be ambient RNA derived in each droplet.  To understand how clustering allows more accurate contamination removal please refer to the paper.
