### ISSUE TITLE
Why do I get contamination fraction >100%

### ISSUE THREAD

**Issue by chansigit** [constantAmateur/SoupX#39]
I used the endothelial marker VWF to estimate the contamination fraction for a group of immune cells.

After running 
`sc <- calculateContaminationFraction(sc=sc, nonExpressedGeneList=nonExpGlist,  useToEst = useToEst_clustering)`

I got
`Estimated global contamination fraction of 114.78%`

How could that be possible? Why does the algorithm return a value more than 100% ?

**Comment by constantAmateur** [comment]
This indicates that the gene you are using to estimate the contamination is genuinely expressed in the cells where SoupX is being told (by the useToEst parameter) it should not be present.  Have you manually constructed useToEst_clustering or is it being produced by `estimateNonExpressingCells`
