### ISSUE TITLE
Performance on 10X v3 libraries

### ISSUE THREAD

**Issue by jpreall** [constantAmateur/SoupX#40]
I have used SoupX successfully in the past on 10X v2 libraries, which have far fewer possible barcodes than the v3 chemistry.  Calculating cell specific estimates takes a few minutes on my laptop on v2 libraries, but many hours on v3 chemistry and ultimately exhausts available vector memory.  Is this a known issue with the current version?  Adjusting counts also seems to hang.   

I also experienced performance problems on a fresh install of R/Rstudio/SoupX on a new iMac.  

Perhaps there is some dependency that is not configured properly on my machines for parallelization?

**Comment by constantAmateur** [comment]
The memory and compute requirements of SoupX should not be particularly high (unless you are opting to use cell specific contamination estimates, which I do not recommend).  Which step exactly is taking hours to run?  Are you providing sparse matricies as inputs?
