### ISSUE TITLE
Is the tutorial is out of date?

### ISSUE THREAD

**Issue by I-Hao** [constantAmateur/SoupX#41]
Hi,

I just download the latest version of the SoupX and try to follow the tutorial:
https://cdn.rawgit.com/constantAmateur/SoupX/master/doc/pbmcTutorial.html
I found the function/format in the v1.2.2 didn't match the tutorial, I'm wondering whether the tutorial can be updated to the current version?

Thanks

I-Hao

**Comment by constantAmateur** [comment]
Yes the tutorial is somewhat out of date, but the changes between the current version and the tutorial should be fairly small and it should be obvious from the documentation for each function what should be done instead.
