### ISSUE TITLE
Error loading 10x data

### ISSUE THREAD

**Issue by anaccsilva** [constantAmateur/SoupX#45]
Hello, I am pretty new to this R world, but I am trying to clean up some data and found SoupX to be the solution. I am trying to follow the vignette provided with the package using my own data and as soon as I tried to run "sc = load10X(dataDirs)", I get the following error:  

> sc = load10X(dataDirs)
Loading raw count data
Error in full.data[[1]] : subscript out of bounds

Can someone help me figuring out the problem, please?
Thanks

**Comment by julicudini** [comment]
I got this error when I tried to give the path to the `raw_feature_bc_matrix` directory instead of the top-level directory that contained that directory. Was fixed by removing `raw_feature_bc_matrix` from the path. And then I had to also remove the backslash from the end of that path or it fails later down the line too. Eventually, I ran into another issue where the programme failed when calling Seurat's "Read10X" function on that directory (a Seurat V2 vs V3 issue?) so ultimately, I don't know if this will help you but might as well try

**Comment by anaccsilva** [comment]
Hi @julicudini , thanks for your comment. I didn't put the whole code before, but I gave the path to the top-level directory containing both raw and filtered files as you said. 

dataDirs = c("soup_x_msg11/")
sc = load10X(dataDirs)

I am wondering if it is a problem with the file. Each one, raw and filtered folders, should have 3 files in each, correct? Barcodes.tsv.gz, features.tsv.gz and matrix.mtx.gz?

**Comment by constantAmateur** [comment]
Hmm, that does sound like a problem with the files or folder structure of your data.  It could also be to do with the meta-data that SoupX tries to automatically load when using 10X data.

Can you try loading the data manually without the helper function with:

```
tod = Seurat::Read10X('soup_x_msg11/raw_feature_bc_matrix')
toc = Seurat::Read10X('soup_x_msg11/filtered_feature_bc_matrix')
sc = SoupChannel(tod,toc)
```

and see if you still get an error?

**Comment by anaccsilva** [comment]
Hi, thanks. It worked.
Sorry for this next question, but as I said previously, I am pretty new to this. I don't know exactly where to restart with this object following the Vignette steps. I tried few options but none worked.

**Comment by constantAmateur** [comment]
You'll need to add clustering information with `setClusters`.  You will need to generate clustering using some other package, such as Seurat.  Usually this is loaded from cellranger, but I suspect there is something non-standard in your analysis folder that is causing `load10X` to fail.  Look at the help for `setClusters` for details how to do this.

If you want to do any of the visualisation steps in the vignette you also need to provide some kind of dimension reduction using `setDR`.  This is not essential, but be aware that some of the visualisation examples in the vignette won't work without it.

After that you should be able to proceed from the section starting "Visual sanity checks" in the vignette.

**Comment by anaccsilva** [comment]
Hello, thanks again for your help. 
Just an update. As we work with a core, all the information that we needed was with them. So they helped me to get the whole cellranger outs folder and it worked just fine.
Thanks a lot!

**Comment by Nur-Taz** [comment]
Hi @anaccsilva and @constantAmateur: I am having the same issue with load10x for the top level cellranger output. 

(1) I can do SoupChannel with tod and toc. But the next step is `estimateSoup` or `setSoupProfile`, right? After which I have to add the metadata, such as the clustering, correct?

(2) When loading tod and toc using `Seurat::Read10X`, what is the purpose of saying "GRCh38"? (on the vignette). Is it necessary for alignment at this stage?

(3) For `setclusters` to work if I can't upload the cellranger outs folder, I have to put my own clustering info. Is that clustering done on the raw_feature_bc_matrix, for example, using Seurat? Or does it have to be done on both raw and filtered bc matrix?

Thanks a lot for your response, and any additional information that you think will help me. For my dataset, I want to get to a point where I can use `autoEstCont`. @anaccsilva: Do you know specifically what your core did that enabled you to load the outs folder? Perhaps I can request my core to do the same for me.

**Comment by ishwarvh** [comment]
Hello, 

I am having this exact issue pop up with Soup 1.6.2.

I am trying to load output files obtained from CellRanger 7.1

The input directory I am pointing to has the "analysis" and the "filtered_feature_bc_matrix folders", which I believe has the necessary information needed for SoupX to do its magic.

Please let me know if there is something I am missing here. 

Thank you,
Ishwar
