### ISSUE TITLE
Request for users to specify more ggplot arguments

### ISSUE THREAD

**Issue by yu-tong-wang** [constantAmateur/SoupX#51]
Hi there, 

Thanks for developing `SoupX`, and it has been a pleasure to try it out so far! Could you allow the users to specify ggplot arguments in the self-defined functions, such as point size, alpha, etc? This would be super helpful!

**Comment by constantAmateur** [comment]
Thanks for the suggestion, the new version will include more options along these lines.  All plot functions return the ggplot object, so many (but not all) of these properties can be changed by modifying the return object.  For example by adding a call to `scale_fill_manual` to the results of `plotMarkerMap`.
