### ISSUE TITLE
Loading data and downstream steps

### ISSUE THREAD

**Issue by Nur-Taz** [constantAmateur/SoupX#52]
Hi @constantAmateur: I am having troubling loading my dataset with `load10x` for the top level cellranger output.

(1) I can do `SoupChannel` with tod and toc. But the next step is `estimateSoup` or `setSoupProfile`, right? After which I have to add the metadata, such as the clustering, correct?

(2) When loading tod and toc using `Seurat::Read10X`, what is the purpose of saying "GRCh38"? (on the vignette). 

(3) For `setclusters` to work if I can't upload the cellranger outs folder, I have to put my own clustering info. Is that clustering done on the raw_feature_bc_matrix, for example, using Seurat? Or does it have to be done on both raw and filtered bc matrix?

Thanks a lot for your response, and any additional information that you think will help me. For my dataset, I want to get to a point where I can use `autoEstCont`.

**Comment by Nur-Taz** [comment]
I solved all the issues I was having, so I'll close the issue.
If anyone drops by this issue, and are interested in learning about the solutions, feel free post and tag me, and I will be happy to share my findings.

**Comment by hothri** [comment]
@Nur-Taz Hi,  Which information have you used for clustering?
