### ISSUE TITLE
Integrating result with Scanpy 

### ISSUE THREAD

**Issue by justinesjw** [constantAmateur/SoupX#6]
Hello! 

From you paper you mention that there's a way to integrate SoupX's result with Seurat and Scanpy.  

I noticed that there is a function (createCleanedSeurat.R) for Seurat. is there such function for Scanpy?

Thanks!

**Comment by justinesjw** [comment]
If anyone is looking for an answer to this problem, i converted the matrix to .mtx using 

> writeMM(sparse_mat, file="outfile.mtx")

and read into scanpy using 

> adata = sc.read('outfile.mtx', cache=True).T

**Comment by constantAmateur** [comment]
The output of SoupX is another sparse matrix, which as you observe can be written out and loaded in any downstream analysis package instead of the uncorrected sparse matrix.
