### ISSUE TITLE
How should the output count table be treated before downstream analysis?

### ISSUE THREAD

**Issue by tkapello** [constantAmateur/SoupX#63]
Sorry for writing as a separate "issue", but the original one was closed too quickly. My confusion is about how one should use the SoupX output. After the correction, numbers are not integers anymore. Would you recomment rounding as you describe in the vignette or using the corrected counts as they are before normalization, scaling and dimensionality reduction?

**Comment by constantAmateur** [comment]
If you're just using Seurat, it is fine to use a non-integer matrix as input.  If you do need for counts to be integers, set `roundToInt=TRUE` when running `adjustCounts`.  Or just round the resulting matrix to integers yourself.
