### ISSUE TITLE
Can I still use SoupX to detect ambient RNA if I do not have filtered gene-barcode matrix?

### ISSUE THREAD

**Issue by rrchai** [constantAmateur/SoupX#67]
Hi,

I just realize the data I have only contains **raw gene-barcode matrix**, but lacks of **filtered gene-barcode matrix**. Can I still use `SoupX` to detect ambient RNA ?

Thank you!

**Comment by constantAmateur** [comment]
As this is a semi-regular request and I may include a function to do this easily in future versions.  For now, look at the section "Profiling the Soup" in the [vignette](https://rawcdn.githack.com/constantAmateur/SoupX/6be48cdb0950ed145a3ca6cf235ec2c24d626f81/inst/doc/pbmcTutorial.html).

By aware that this approach explicitly assumes that the background profile is the same as the average expression across all cells.  This is in general a reasonable assumption (see [paper](https://academic.oup.com/gigascience/article/9/12/giaa151/6049831)), but there will be inaccuracies as a result.  In particular stress response genes like MT will likely have a higher background fraction than suggested by the average across all cells.
