### ISSUE TITLE
Setting contamination rate manually does not emprove the correction

### ISSUE THREAD

**Issue by akramdi** [constantAmateur/SoupX#69]
Hello, 

Following the recommendations on when a data  still looks contaminated after correction, I tried increasing the contamination rate from the estimated one using HB genes (%3) to 10%, then 20% using: 

conta=0.1 #or 0.2
sc=setContaminationFraction(sc,conta)
out = adjustCounts(sc, roundToInt=TRUE)

This does not change the contamination: it looks unchanged and I still see background expression of a gene in clusters where it should not be expressed (this was also confirmed by `plotMarkerMap` plot)

Are these the right command ? We just need to set the contamination then adjust the count, right?

Thanks for the help.
Best,

**Comment by constantAmateur** [comment]
`plotMarkerMap` does not plot the corrected counts, you need some downstream tool (like Seurat) to do that.  The code you have described will change the contamination rate and result in a different output matrix.  If you want to confirm this, store both versions and then check if `out1 == out2`.
