### ISSUE TITLE
Add option to save plot in autoEstCont

### ISSUE THREAD

**Issue by Hrovatin** [constantAmateur/SoupX#70]
Add option to save plot in autoEstCont so that if correcting multiple files non-interactively plots can be inspected afterwards.

**Comment by constantAmateur** [comment]
This is a good suggestion, I will implement it in the next version.  Thank you!

**Comment by ms-gx** [comment]
Yes, please! Is there no option to catch the plot in a non-interactive script?

**Comment by ms-gx** [comment]
Ah, can be captured with a normal png() & dev.off() in the script

**Comment by AmelZulji** [comment]
Hi folks,

Is there any update on this?

it would be pretty convenient if one could output ggplot class, so that it can be combined witt other plots using patchwork or similar. 

Best,
Amel
