### ISSUE TITLE
On setting mouse transcripts as 0 in scRNA-Seq experiment 

### ISSUE THREAD

**Issue by Jay-Leung** [constantAmateur/SoupX#78]
Thank you for this useful package! I am new to scRNA-Seq and recently have acquired some data pertaining to Patient-Derived Xenografts. I was thinking to set the mouse genes to 0 to calculate ambient RNA expression - in the paper, the mouse genes were set to 0 in the human cells and vice versa, but I could not find the exact documentation for that. How would I know which genes are mouse specific? Thanks!

**Comment by constantAmateur** [comment]
If I have understood correctly, it sounds like you only interested in the human cells and not the native mouse cells.  I would do the following:
 
  1. Run `useToEst = estimateNonExpressingCells(sc, nonExpressedGeneList = list(mouseGenes = namesOfMouseGenesHere))`
  2. Run `sc = calculateContaminationFraction(sc, list(mouseGenes = namesOfMouseGenesHere), useToEst = useToEst)`
  3. Calculate the corrected matrix as usual with `adjustCounts`
  4. Manually remove all the rows of the final matrix corresponding to mouse genes.
