### ISSUE TITLE
issue in plotMarkerDistribution, dimnames error

### ISSUE THREAD

**Issue by kerkhoffwilla** [constantAmateur/SoupX#79]
Hi,

I am trying to use plotMarkerDistribution to estimate a non-expressed gene list for my clusters and I keep getting the same error: 

> plotMarkerDistribution(sc1)
No gene lists provided, attempting to find and plot cluster marker genes.
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)

This is my first attempt working with SoupX and I'm relatively new to R as well, I would appreciate any guidance. I'm not sure what other information you need to understand my issue here, I'm attaching my script as a start. 

[M1new_Soupx_01_textfile.txt](https://github.com/constantAmateur/SoupX/files/6386550/M1new_Soupx_01_textfile.txt)

Thanks!
Willa

**Comment by constantAmateur** [comment]
It's quite hard to guess exactly what is the problem from the error code.  Looking at your script you look like you're doing a lot of things manually when it appears you're using 10X data generated by cellranger.  I would suggest trying to use the standard load10X functions and see if that fixes your issue.

Failing that, try explicitly providing a few genes to `plotMarkerDistribution` via the `nonExpressedGeneList` parameter and see if that works.  That will at least tell you if the error is occurring in the part of the function that tries to identify genes that might be interesting or in the main body of the function.
