### ISSUE TITLE
CRAN version not working

### ISSUE THREAD

**Issue by ONeillMB1** [constantAmateur/SoupX#80]
Hello, I'm trying to install the latest version of SoupX and I get the following error:
> install.packages('SoupX')
Warning message:
package 'SoupX' is not available (for R version 3.6.3) 

It also appears the package has been removed from CRAN:
package ‘SoupX’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2021-04-10 as check problems were not corrected in time.

A summary of the most recent check results can be obtained from the check results archive.

Please use the canonical form https://CRAN.R-project.org/package=SoupX to link to this page.

Any plans to remedy this in the near future?

Thank you,

Mary

**Comment by constantAmateur** [comment]
The newest version is CRAN compliant and it should be back in CRAN soon.  Thanks for bringing it to my attention.
