### ISSUE TITLE
Loading count matrix  

### ISSUE THREAD

**Issue by Jemkon** [constantAmateur/SoupX#9]
Hi,

I have been using SoupX for my 10X data and it seems to be working great. 

But I am having issues with SoupX when I try to load count matrix. I have one count matrix. How do I create subset of it to remove empty droplets?

Here are commands:

    tod <- read.delim("Maligant50.csv", row.names = 1, sep=",")    
    toc <- read.delim("Maligant50.csv", row.names = 1, sep=",")    

    channel1 = SoupChannel(tod,toc,channelName="channel1")
    spObj = SoupChannelList(list(channel1))
    spObj$channels$channel1 = estimateSoup(spObj$channels$channel1)

I am getting following error:

    spObj$channels$channel1 = estimateSoup(spObj$channels$channel1)
    Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
      'x' must be an array of at least two dimensions

Am I doing anything wrong?

Many thanks,

**Comment by spalit** [comment]
Hi, 
I am also currently facing a similar issue. With 10X raw and filtered files, SoupX works quite well. However, I am not quite sure how one could estimate the soup with just a table of counts. Would be really helpful if you can share a workaround in case you have managed to find one. Many thanks in advance!

**Comment by constantAmateur** [comment]
Hmm, this looks like an issue with the loading of the sparse matrix row/column sum functions.  I will try and track down the exact cause, but in the meantime I would suggest running the following before you execute the function currently throwing an error:

```
library(Matrix)
rowSums = Matrix::rowSums
colSums = Matrix::colSums
```

**Comment by Jemkon** [comment]
Many thanks Matthew. I have tried running above code but got the same error. 

    tod <- read.delim("Maligant50.csv", row.names = 1, sep=",")    
    toc <- read.delim("Maligant50.csv", row.names = 1, sep=",")    
    
    channel1 = SoupChannel(tod,toc,channelName="channel1")
    spObj = SoupChannelList(list(channel1))

    library(Matrix)
    rowSums = Matrix::rowSums 
    colSums = Matrix::colSums
    
    spObj$channels$channel1 = estimateSoup(spObj$channels$channel1)

    Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
      'x' must be an array of at least two dimensions

Have you had a chance to look at the actual cause for this error?

@spalit did you manage to find the workaround for the above issue of loading data in SoupX?

Many thanks,
Jemkon

**Comment by Jemkon** [comment]
> Hmm, this looks like an issue with the loading of the sparse matrix row/column sum functions. I will try and track down the exact cause, but in the meantime I would suggest running the following before you execute the function currently throwing an error:
> 
> ```
> library(Matrix)
> rowSums = Matrix::rowSums
> colSums = Matrix::colSums
> ```

Many thanks Matthew. I have tried running above code but got the same error.

    tod <- read.delim("Maligant50.csv", row.names = 1, sep=",")    
    toc <- read.delim("Maligant50.csv", row.names = 1, sep=",")    
    
    channel1 = SoupChannel(tod,toc,channelName="channel1")
    spObj = SoupChannelList(list(channel1))
    
    library(Matrix)
    rowSums = Matrix::rowSums 
    colSums = Matrix::colSums
    
    spObj$channels$channel1 = estimateSoup(spObj$channels$channel1)
    
    Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
      'x' must be an array of at least two dimensions

Have you had a chance to look at the actual cause for this error?

@spalit did you manage to find the workaround for the above issue of loading data in SoupX?

Many thanks,
Jemkon

**Comment by alejandro-jimenezsanchez** [comment]
Hi,

I got the same error, but found the source of it. To prevent that error you just have to do:

`channel1 = SoupChannel(tod,toc,channelName="Channel1", keepDroplets = TRUE)`

Otherwise `keepDroplets` is `FALSE` by default, and your `channel1` object does not have the `tod` list stored.

`estimateSoup` has this line of code: 

`sc$soupProfile = estRateLims(rowSums(sc$tod[,w,drop=FALSE]),sum(sc$tod[,w]))`

If `sc` does not have `tod`, then that results in `NULL` and `rowSums` complains of course.

**Comment by ivonyao** [comment]
I tried the same code, I still get the same error.
basically what I did is:
count=read.delim("count.csv", row.names = 1, sep=",") 
tod=count
toc=count
sc = SoupChannel(tod, toc, keepDroplets = TRUE)
sc=estimateSoup(sc)


I am getting the same error

Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

Any comments?

**Comment by brianpenghe** [comment]
I've got the same error

**Comment by nonafarbehi2018** [comment]
Hi all, 
I got the same error. Has anyone sort the problem out?

**Comment by hviolaphd** [comment]
Hey guys, I solved this issue for those who didn't get the other solution to work. The problem is that even if you keep droplets, the 'tod' data isn't saved in the soupx object. You have to manually add it: 

sc$tod <- tod

that will enable the rest of the code to run. This seems like a dev bug

**Comment by ridvan-cetin** [comment]
I had the same issue using `R version 4.5.0 (2025-04-11)` , `Seurat_5.3.0 `, and `SoupX_1.6.2`. I think the main problems are `colnames` and `rownames` of  `toc` and `tod`.  Here is the process that worked on me:

**Prepare `tod`**
`colnames(raw_obj@assays$RNA@layers$counts) <- rownames(raw_obj@meta.data)`
`rownames(raw_obj@assays$RNA@layers$counts) <- rownames(raw_obj)`
`head(raw_obj@assays$RNA@layers$counts)`
`tod <- raw_obj@assays$RNA@layers$counts`
`str(tod)` 
You should see the following as a part of the `str(tod)` output (gene symbols and cell id):
`  ..@ Dimnames:List of 2`
 ` .. ..$ : chr [1:27998] "Xkr4" "Gm1992" "Gm37381" "Rp1" ...`
 `.. ..$ : chr [1:1500984] "AAACCCAAGAAACACT-1" "AAACCCAAGAAACCCA-1" "AAACCCAAGAAACCCG-1" "AAACCCAAGAAAGCGA-1" ...`

**Prepare `toc`**
`colnames(obj@assays$RNA@layers$counts) <- rownames(obj@meta.data)`
`rownames(obj@assays$RNA@layers$counts) <- rownames(obj)`
`head(obj@assays$RNA@layers$counts)`
`toc <- obj@assays$RNA@layers$counts`
`str(toc)`
You should see the following as a part of the `str(tod)` output (gene symbols and cell id) (as above).


**Running `SoupChannel`**
`sc = SoupChannel(
  raw_obj@assays$RNA@layers$counts,
  obj@assays$RNA@layers$counts,
  calcSoupProfile = FALSE,  keepDroplets = TRUE
)`

or
`sc = SoupChannel(
  tod,
  toc,
  calcSoupProfile = FALSE,  keepDroplets = TRUE
)`

**Check the `str(sc)**
See the `toc` and `tod` present, and they both have gene symbols and cell IDs.


**Running `sc = estimateSoup(sc)`**
`sc = estimateSoup(sc)`

**Assign the cluster information**
`clusters <- setNames(obj@meta.data$soupX_cluster_1.2, rownames(obj@meta.data))`
`sc <- setClusters(sc, clusters)`

**Run `autoEstCont()**
`sc <- autoEstCont(sc, doPlot=TRUE)`
