### ISSUE TITLE
Error in quickMarkers

### ISSUE THREAD

**Issue by vertesy** [constantAmateur/SoupX#92]
Hi Matthew,

I encounter this error when running quickMarkers:

```r
mrks = SoupX::quickMarkers(toc = combined.obj@assays$RNA@counts, clusters = "integrated_snn_res.0.5")
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

Could you please help with some hints? 
Thank you!

**Comment by constantAmateur** [comment]
Clusters needs to be a vector, not the name of meta.data column in the Seurat object.  To run on a seurat object do
```
mrks = SoupX::quickMarkers(toc = srat@assays$RNA@counts,clusters=srat@meta.data$integrated_snn_res.0.5)
```

**Comment by alexlenail** [comment]
I'm getting this error message when I run `autoEstCont` for one of my 96 samples.

**Comment by alexlenail** [comment]
This is happening because 10X assigned all cells in this sample to a single cluster. Perhaps it would be nice to have a handler for that case, @constantAmateur
