### ISSUE TITLE
Error while manually selecting gene list to determine contamination fraction

### ISSUE THREAD

**Issue by samyuktha-suresh** [constantAmateur/SoupX#95]
Hello! Thanks so much for developing this really cool package! I have recently starting learning how to analyse scRNA data and was trying to use a gene list to manually determine the contamination fraction using SoupX. I was able to run the 'autoEstcont' function but wanted to try the manual method to improve the filtering process. However I am running into this error that appears once the gene list is created. 
'useToEst = estimateNonExpressingCells(soup.channel, nonExpressedGeneList = list(IG = igGenes))'
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : invalid character indexing.

I tried both with the vignette gene list and a gene list relevant to my dataset but that did not solve the problem. Has anyone else run into this issue or would you be able to give me some way to work this out?

Thanks so much!
Sam

**Comment by constantAmateur** [comment]
Hi Sam.  That sounds very much like an issue with gene names not matching.  I would make sure that you are using the same type of IDs (e.g. ENSEMBL) for bot the soup.channel object and the igGenes.
