### ISSUE TITLE
Estimated global rho inconsistent with the post rho/rho max in the plot

### ISSUE THREAD

**Issue by jon-xu** [constantAmateur/SoupX#96]
Hi constantAmateur,

Thanks for the great package!
I just met an interesting thing when I used the quick start autoEstCont on my dataset that the Estimated global rho is 0.08 (as below), which is different from the post rho or rho max (0.22) in the plot, not sure which one is correct, please?

Warning message in sparseMatrix(i = out@i[w] + 1, j = out@j[w] + 1, x = out@x[w], :
"'giveCsparse' has been deprecated; setting 'repr = "T"' for you"
Expanding counts from 13 clusters to 13106 cells.
Loading raw count data
10X data contains more than one type and is being returned as a list containing matrices of each type.
Loading cell-only count data
10X data contains more than one type and is being returned as a list containing matrices of each type.
Loading extra analysis data where available
71 genes passed tf-idf cut-off and 46 soup quantile filter.  Taking the top 46.
Using 214 independent estimates of rho.
Estimated global rho of 0.08

**Comment by constantAmateur** [comment]
It's hard to know what you mean without an image, but the estimated global rho (8% in your case) is the one you should use.
