### ISSUE TITLE
Preserving ensembl IDs post SoupX

### ISSUE THREAD

**Issue by Jay-Leung** [constantAmateur/SoupX#97]
Hello Team,

Thanks for the great and neat package. I have been using it on 10x scRNA-Seq data. However, for downstream analysis I wish to use ensembl IDs, which isn't preserved in the postSoupX features file.

My code is as follows: 

# load raw and filtered matrix
`sc = load10X(dataDir = "Data/Post Xenocell 10x Cell Ranger Count/RHB251019RL-XCG_run1_21052021/outs")`

`clusters <- read.csv("Data/Post Xenocell 10x Cell Ranger Count/RHB251019RL-XCG_run1_21052021/outs/analysis/clustering/graphclust/clusters.csv", row.names = 1)`

#Set clusters, LOAD cluster data
`sc = setClusters(sc, setNames(clusters$Cluster, rownames(clusters)))`

#Automated calculation of contamination
`sc = autoEstCont(sc, tfidfMin = 1.0)`

###Soup specific genes
`head(sc$soupProfile[order(sc$soupProfile$est,decreasing=TRUE),],n=20)`
`plotMarkerDistribution(sc)`

#Correct expression profile 
`out = adjustCounts(sc, roundToInt=TRUE)`

###Generate 10x format file
`DropletUtils:::write10xCounts('./Data/Post Xenocell 10x Cell Ranger Count/RHB251019RL-XCG_run1_21052021/outs/postSoupX',out, version = "3")`

If I unzip the features file prior to SoupX, I see 3 columns with ensembl IDs,
![pre-SoupX](https://user-images.githubusercontent.com/82377547/147037712-5c974f69-d5e5-439e-9f8d-6f4b9233355b.PNG)

whereas in the features file after postSoupX, the ensembl IDs are replaced by gene symbols. 
![postSoupX](https://user-images.githubusercontent.com/82377547/147037716-4ac17f3d-5415-48aa-a39a-3c83acb1bd04.PNG)

If I take a closer look at the soup channel object, it includes only 2 dimensions - barcodes (column names) and gene symbols (rownames). 
![soupchanneldims](https://user-images.githubusercontent.com/82377547/147037781-dbb66b8d-2549-4030-bdaa-db00a60717f0.PNG)

I thought this could be toggled with the load10x function, but I do not see any parameters that allow me to do so. Perhaps the arguments `readArgs = list()` or `includeFeatures = c("Gene Expression")` could be used, but I am not sure how. Could you clarify?

Thanks!

Regards,
Jay

**Comment by Jay-Leung** [comment]
Hello,

Just to add on, if I use `Seurat::Read10x(data.dir, gene.columns = 1)  ## use ensembl IDs for genes` to manually create the SoupX object, I can get the enseml IDs in the soup channel object. However, I would lose the gene symbols when I write the 10x file eventually:

![Read10xSoupX](https://user-images.githubusercontent.com/82377547/147040852-33f54426-ebc3-4607-96db-cbe1b58acf32.PNG)

So my question is if there is a way to output the postSoupX features file in the same way as the initial features file with both the ensembl IDs and gene symbols inside.

Thanks!

**Comment by constantAmateur** [comment]
This is really not a SoupX issue, as it is the Seurat `Read10X` function that only keeps one gene name column.  My personal approach is to load the features.tsv.gz file into a table and then store it in the `@misc` slot of the Seurat object so that I can convert between them as needed.  You could use the same approach with the `SoupChannel` object, which is really just a list.  So you could do something like:
```
sc$geneTable = read.table('features.tsv.gz',header=TRUE)
```

I hope this helps.

**Comment by CWYuan08** [comment]
> Hello,
> 
> Just to add on, if I use `Seurat::Read10x(data.dir, gene.columns = 1) ## use ensembl IDs for genes` to manually create the SoupX object, I can get the enseml IDs in the soup channel object. However, I would lose the gene symbols when I write the 10x file eventually:
> 
> ![Read10xSoupX](https://user-images.githubusercontent.com/82377547/147040852-33f54426-ebc3-4607-96db-cbe1b58acf32.PNG)
> 
> So my question is if there is a way to output the postSoupX features file in the same way as the initial features file with both the ensembl IDs and gene symbols inside.
> 
> Thanks!

Hi I am wondering if this has been fixed, many thanks!

Best,
CW
