### ISSUE TITLE
cellranger multi support?

### ISSUE THREAD

**Issue by pjlmac** [constantAmateur/SoupX#99]
I hate being that person, but I was wondering if SoupX has a configuration for cellranger multi or if there is one planned. This program works so beautifully in individual datasets and I would love to use it with a multiplexed sample. For mine, my project uses the cell hashing/antibody tagging metric detrived from Aviv Regev's group and related developments/enhancements pertaining her work. Thanks!

**Comment by Sethupathy-Lab** [comment]
I'd like to second this. I use SoupX regularly for my 10x single cell datasets, but recently started working with a multiplex dataset and don't see a straightforward and easy workaround for applying SoupX to the outputs of cellranger multi. Thank you!

**Comment by constantAmateur** [comment]
Sorry to disappoint, but I am unlikely to do this.  The reason being that there is another method specifically tailored to multiplexed data, [souporcell](https://github.com/wheaton5/souporcell).  

With multiplexed data the mixing of genotypes gives another layer of information that can be used to estimate the contamination fraction.  Souporcell is built from the ground up to use this information and so will perform better on multiplexed data.  I would recommend using souporcell for this type of data.
